-- Database Index Optimization Script
-- Generated by optimize_database_queries.py

-- Index for clinical_records.clinic_id
CREATE INDEX idx_clinical_records_clinic_id ON clinical_records(clinic_id);

-- Index for clinical_records.patient_id
CREATE INDEX idx_clinical_records_patient_id ON clinical_records(patient_id);

-- Index for invoices.clinic_id
CREATE INDEX idx_invoices_clinic_id ON invoices(clinic_id);

-- Index for payments.status
CREATE INDEX idx_payments_status ON payments(status);

-- Index for stock_movements.movement_date
CREATE INDEX idx_stock_movements_movement_date ON stock_movements(movement_date);

