"""Add return visit management

Revision ID: 7a605a27f1ac
Revises: add_return_approval_requests
Create Date: 2026-01-29 13:45:16.805512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7a605a27f1ac'
down_revision: Union[str, None] = 'add_return_approval_requests'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insurance_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('insurance_company', sa.String(length=200), nullable=False),
    sa.Column('ans_registration', sa.String(length=6), nullable=False),
    sa.Column('coverage_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('requires_preauth', sa.Boolean(), nullable=False),
    sa.Column('max_annual_limit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('max_procedure_limit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insurance_plans_ans_registration'), 'insurance_plans', ['ans_registration'], unique=False)
    op.create_index(op.f('ix_insurance_plans_id'), 'insurance_plans', ['id'], unique=False)
    op.create_index(op.f('ix_insurance_plans_name'), 'insurance_plans', ['name'], unique=False)
    op.create_table('preauth_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('insurance_plan_id', sa.Integer(), nullable=False),
    sa.Column('procedure_code', sa.String(length=10), nullable=False),
    sa.Column('procedure_description', sa.String(length=200), nullable=False),
    sa.Column('requested_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('approved_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'DENIED', 'EXPIRED', 'CANCELLED', name='preauthstatus'), nullable=False),
    sa.Column('request_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('response_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('authorization_number', sa.String(length=50), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['insurance_plan_id'], ['insurance_plans.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_preauth_requests_id'), 'preauth_requests', ['id'], unique=False)
    op.create_table('system_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('clinic_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_logs_clinic_id'), 'system_logs', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_system_logs_id'), 'system_logs', ['id'], unique=False)
    op.create_index(op.f('ix_system_logs_level'), 'system_logs', ['level'], unique=False)
    op.create_index(op.f('ix_system_logs_source'), 'system_logs', ['source'], unique=False)
    op.create_index(op.f('ix_system_logs_timestamp'), 'system_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_system_logs_user_id'), 'system_logs', ['user_id'], unique=False)
    op.drop_index(op.f('ix_migration_jobs_clinic_id'), table_name='migration_jobs')
    op.drop_index(op.f('ix_migration_jobs_created_by'), table_name='migration_jobs')
    op.drop_index(op.f('ix_migration_jobs_id'), table_name='migration_jobs')
    op.drop_table('migration_jobs')
    
    # Skip activations column changes - they cause foreign key type mismatch
    # The activations table already exists with proper types
    # op.alter_column('activations', 'id', ...)
    # op.alter_column('activations', 'license_id', ...)
    
    # Create return visit management tables
    op.create_table('return_visit_configs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('clinic_id', sa.Integer(), nullable=False),
        sa.Column('doctor_id', sa.Integer(), nullable=False),
        sa.Column('enable_return_limit', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('return_window_days', sa.Integer(), nullable=False, server_default='30'),
        sa.Column('daily_return_limit', sa.Integer(), nullable=False, server_default='5'),
        sa.Column('monthly_return_limit', sa.Integer(), nullable=True),
        sa.Column('require_approval_when_exceeded', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('approval_message', sa.String(length=500), nullable=True),
        sa.Column('custom_rules', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_return_visit_configs_id'), 'return_visit_configs', ['id'], unique=False)
    op.create_index('ix_return_visit_configs_clinic_doctor', 'return_visit_configs', ['clinic_id', 'doctor_id'], unique=False)
    
    op.create_table('return_visit_approvals',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('clinic_id', sa.Integer(), nullable=False),
        sa.Column('appointment_id', sa.Integer(), nullable=False),
        sa.Column('patient_id', sa.Integer(), nullable=False),
        sa.Column('doctor_id', sa.Integer(), nullable=False),
        sa.Column('requested_by', sa.Integer(), nullable=False),
        sa.Column('reason', sa.String(length=500), nullable=False),
        sa.Column('status', sa.String(length=20), nullable=False, server_default='pending'),
        sa.Column('approved_by', sa.Integer(), nullable=True),
        sa.Column('approval_notes', sa.String(length=500), nullable=True),
        sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['requested_by'], ['users.id']),
        sa.ForeignKeyConstraint(['approved_by'], ['users.id']),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_return_visit_approvals_id'), 'return_visit_approvals', ['id'], unique=False)
    op.create_index('ix_return_visit_approvals_status', 'return_visit_approvals', ['status'], unique=False)
    op.create_index('ix_return_visit_approvals_created_at', 'return_visit_approvals', ['created_at'], unique=False)
    op.alter_column('budgets', 'status',
               existing_type=postgresql.ENUM('draft', 'sent', 'accepted', 'rejected', 'converted', 'expired', name='budgetstatus'),
               type_=sa.Enum('DRAFT', 'SENT', 'ACCEPTED', 'REJECTED', 'CONVERTED', 'EXPIRED', name='budgetstatus', native_enum=False),
               existing_nullable=False)
    op.drop_index(op.f('idx_clinical_records_created_at'), table_name='clinical_records')
    op.alter_column('document_signatures', 'document_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('PRESCRIPTION', 'CERTIFICATE', 'CONSULTATION_REPORT', 'EXAM_REQUEST', 'OTHER', name='documenttype', native_enum=False),
               existing_nullable=False)
    op.alter_column('document_signatures', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('PENDING', 'SIGNED', 'REVOKED', 'EXPIRED', name='signaturestatus', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'signed'::character varying"))
    op.drop_index(op.f('ix_document_signatures_doc_type_id'), table_name='document_signatures')
    op.drop_constraint(op.f('document_signatures_clinic_id_fkey'), 'document_signatures', type_='foreignkey')
    op.drop_constraint(op.f('document_signatures_doctor_id_fkey'), 'document_signatures', type_='foreignkey')
    op.create_foreign_key(None, 'document_signatures', 'users', ['doctor_id'], ['id'])
    op.create_foreign_key(None, 'document_signatures', 'clinics', ['clinic_id'], ['id'])
    
    # Skip entitlements column changes - they cause foreign key type mismatch
    # The entitlements table already exists with proper types
    # op.alter_column('entitlements', 'id', ...)
    # op.alter_column('entitlements', 'license_id', ...)
    op.alter_column('expenses', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('PENDING', 'PAID', 'CANCELLED', name='expensestatus', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('expenses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_help_articles_clinic_id'), table_name='help_articles')
    op.drop_index(op.f('ix_icd10_categories_group_code'), table_name='icd10_categories')
    op.drop_index(op.f('ix_icd10_categories_code'), table_name='icd10_categories')
    op.create_index('ix_icd10_categories_code', 'icd10_categories', ['code'], unique=False)
    op.create_unique_constraint(None, 'icd10_categories', ['code'])
    op.create_unique_constraint(None, 'icd10_chapters', ['code'])
    op.drop_index(op.f('ix_icd10_groups_chapter_code'), table_name='icd10_groups')
    op.create_unique_constraint(None, 'icd10_groups', ['code'])
    op.drop_index(op.f('ix_icd10_search_index_code'), table_name='icd10_search_index')
    op.drop_index(op.f('ix_icd10_search_index_parent_code'), table_name='icd10_search_index')
    op.create_index('ix_icd10_search_code', 'icd10_search_index', ['code'], unique=False)
    op.create_index('ix_icd10_search_parent', 'icd10_search_index', ['parent_code'], unique=False)
    op.drop_index(op.f('ix_icd10_subcategories_category_code'), table_name='icd10_subcategories')
    op.create_unique_constraint(None, 'icd10_subcategories', ['code'])
    op.drop_index(op.f('idx_invoices_issue_date'), table_name='invoices')
    op.drop_index(op.f('idx_invoices_status'), table_name='invoices')
    op.alter_column('medical_terms', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index(op.f('ix_medical_terms_category'), table_name='medical_terms')
    op.create_index(op.f('ix_medical_terms_id'), 'medical_terms', ['id'], unique=False)
    op.drop_index(op.f('idx_message_threads_clinic_id'), table_name='message_threads')
    op.drop_index(op.f('idx_message_threads_patient_id'), table_name='message_threads')
    op.drop_index(op.f('idx_message_threads_provider_id'), table_name='message_threads')
    op.create_index(op.f('ix_message_threads_clinic_id'), 'message_threads', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_message_threads_id'), 'message_threads', ['id'], unique=False)
    op.create_index(op.f('ix_message_threads_patient_id'), 'message_threads', ['patient_id'], unique=False)
    op.create_index(op.f('ix_message_threads_provider_id'), 'message_threads', ['provider_id'], unique=False)
    op.drop_constraint(op.f('message_threads_clinic_id_fkey'), 'message_threads', type_='foreignkey')
    op.drop_constraint(op.f('message_threads_provider_id_fkey'), 'message_threads', type_='foreignkey')
    op.drop_constraint(op.f('message_threads_patient_id_fkey'), 'message_threads', type_='foreignkey')
    op.create_foreign_key(None, 'message_threads', 'clinics', ['clinic_id'], ['id'])
    op.create_foreign_key(None, 'message_threads', 'users', ['provider_id'], ['id'])
    op.create_foreign_key(None, 'message_threads', 'patients', ['patient_id'], ['id'])
    op.alter_column('messages', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('SENT', 'DELIVERED', 'READ', name='messagestatus', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'sent'::character varying"))
    op.alter_column('messages', 'attachments',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('messages', 'medical_context',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index(op.f('idx_messages_created_at'), table_name='messages')
    op.drop_index(op.f('idx_messages_sender_id'), table_name='messages')
    op.drop_index(op.f('idx_messages_thread_id'), table_name='messages')
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_index(op.f('ix_messages_thread_id'), 'messages', ['thread_id'], unique=False)
    op.drop_constraint(op.f('messages_thread_id_fkey'), 'messages', type_='foreignkey')
    op.drop_constraint(op.f('messages_sender_id_fkey'), 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'message_threads', ['thread_id'], ['id'])
    op.create_foreign_key(None, 'messages', 'users', ['sender_id'], ['id'])
    op.create_index(op.f('ix_patient_calls_id'), 'patient_calls', ['id'], unique=False)
    op.drop_constraint(op.f('patient_telemetry_patient_id_fkey'), 'patient_telemetry', type_='foreignkey')
    op.drop_constraint(op.f('patient_telemetry_recorded_by_fkey'), 'patient_telemetry', type_='foreignkey')
    op.drop_constraint(op.f('patient_telemetry_clinic_id_fkey'), 'patient_telemetry', type_='foreignkey')
    op.create_foreign_key(None, 'patient_telemetry', 'patients', ['patient_id'], ['id'])
    op.create_foreign_key(None, 'patient_telemetry', 'clinics', ['clinic_id'], ['id'])
    op.create_foreign_key(None, 'patient_telemetry', 'users', ['recorded_by'], ['id'])
    op.drop_index(op.f('idx_patients_created_at'), table_name='patients')
    op.drop_index(op.f('idx_patients_is_active'), table_name='patients')
    op.drop_index(op.f('idx_payments_paid_at'), table_name='payments')
    op.drop_index(op.f('ix_payments_invoice_id'), table_name='payments')
    op.drop_index(op.f('idx_products_is_active'), table_name='products')
    op.drop_index(op.f('ix_push_subscriptions_endpoint'), table_name='push_subscriptions')
    op.create_index(op.f('ix_push_subscriptions_id'), 'push_subscriptions', ['id'], unique=False)
    op.drop_constraint(op.f('fk_push_subscriptions_user_id'), 'push_subscriptions', type_='foreignkey')
    op.create_foreign_key(None, 'push_subscriptions', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('idx_stock_movements_clinic_id'), table_name='stock_movements')
    op.drop_index(op.f('idx_stock_movements_timestamp'), table_name='stock_movements')
    op.drop_index(op.f('ix_support_tickets_clinic_id'), table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_patient_id'), table_name='support_tickets')
    op.create_index(op.f('ix_symptom_icd10_mappings_icd10_code'), 'symptom_icd10_mappings', ['icd10_code'], unique=False)
    op.create_index(op.f('ix_symptom_icd10_mappings_symptom_id'), 'symptom_icd10_mappings', ['symptom_id'], unique=False)
    op.drop_constraint(op.f('symptom_icd10_mappings_symptom_id_fkey'), 'symptom_icd10_mappings', type_='foreignkey')
    op.create_foreign_key(None, 'symptom_icd10_mappings', 'symptoms', ['symptom_id'], ['id'])
    op.alter_column('tasks', 'priority',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('LOW', 'MEDIUM', 'HIGH', name='taskpriority', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'Média'::character varying"))
    op.create_index('ix_tiss_attachments_guide', 'tiss_attachments', ['guide_id', 'guide_type'], unique=False)
    op.create_index(op.f('ix_tiss_attachments_id'), 'tiss_attachments', ['id'], unique=False)
    op.drop_index(op.f('ix_tiss_audit_logs_entity_type_id'), table_name='tiss_audit_logs')
    op.create_index('ix_tiss_audit_logs_clinic_created', 'tiss_audit_logs', ['clinic_id', 'created_at'], unique=False)
    op.create_index('ix_tiss_audit_logs_entity', 'tiss_audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_tiss_audit_logs_id'), 'tiss_audit_logs', ['id'], unique=False)
    op.create_index('ix_tiss_batches_clinic_status', 'tiss_batches', ['clinic_id', 'submission_status'], unique=False)
    op.create_index(op.f('ix_tiss_batches_id'), 'tiss_batches', ['id'], unique=False)
    op.alter_column('tiss_config', 'prestador',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('tiss_config', 'operadora',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('tiss_config', 'defaults',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('tiss_config', 'tiss',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_constraint(op.f('tiss_config_clinic_id_key'), 'tiss_config', type_='unique')
    op.drop_index(op.f('uq_tiss_config_clinic'), table_name='tiss_config')
    op.create_unique_constraint('uq_tiss_config_clinic', 'tiss_config', ['clinic_id'])
    op.create_index('ix_tiss_consultation_guides_clinic_status', 'tiss_consultation_guides', ['clinic_id', 'status'], unique=False)
    op.create_index(op.f('ix_tiss_consultation_guides_id'), 'tiss_consultation_guides', ['id'], unique=False)
    op.create_index('ix_tiss_hospitalization_guides_clinic_status', 'tiss_hospitalization_guides', ['clinic_id', 'status'], unique=False)
    op.create_index(op.f('ix_tiss_hospitalization_guides_id'), 'tiss_hospitalization_guides', ['id'], unique=False)
    op.create_index(op.f('ix_tiss_individual_fees_id'), 'tiss_individual_fees', ['id'], unique=False)
    op.create_index('ix_tiss_sadt_guides_clinic_status', 'tiss_sadt_guides', ['clinic_id', 'status'], unique=False)
    op.create_index(op.f('ix_tiss_sadt_guides_id'), 'tiss_sadt_guides', ['id'], unique=False)
    op.create_index('ix_tiss_statements_clinic_tipo', 'tiss_statements', ['clinic_id', 'tipo_demonstrativo'], unique=False)
    op.create_index(op.f('ix_tiss_statements_id'), 'tiss_statements', ['id'], unique=False)
    op.alter_column('tiss_templates', 'variables',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.create_index(op.f('ix_tiss_tuss_codes_id'), 'tiss_tuss_codes', ['id'], unique=False)
    op.alter_column('tiss_tuss_version_history', 'motivo',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.create_index(op.f('ix_tiss_tuss_version_history_id'), 'tiss_tuss_version_history', ['id'], unique=False)
    op.drop_constraint(op.f('tiss_versions_version_key'), 'tiss_versions', type_='unique')
    op.create_index(op.f('ix_tiss_versions_id'), 'tiss_versions', ['id'], unique=False)
    op.drop_constraint(op.f('user_roles_name_key'), 'user_roles', type_='unique')
    op.alter_column('user_settings', 'notifications',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('user_settings', 'privacy',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('user_settings', 'appearance',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('user_settings', 'security',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_constraint(op.f('user_settings_user_id_key'), 'user_settings', type_='unique')
    op.drop_index(op.f('ix_user_settings_user_id'), table_name='user_settings')
    op.create_index(op.f('ix_user_settings_user_id'), 'user_settings', ['user_id'], unique=True)
    op.create_index(op.f('ix_user_settings_id'), 'user_settings', ['id'], unique=False)
    op.drop_constraint(op.f('fk_user_settings_user'), 'user_settings', type_='foreignkey')
    op.create_foreign_key(None, 'user_settings', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('idx_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_voice_commands_session_id'), table_name='voice_commands')
    op.create_index(op.f('ix_voice_commands_id'), 'voice_commands', ['id'], unique=False)
    op.alter_column('voice_configurations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index(op.f('ix_voice_configurations_clinic_id'), table_name='voice_configurations')
    op.drop_index(op.f('ix_voice_configurations_user_id'), table_name='voice_configurations')
    op.create_index(op.f('ix_voice_configurations_id'), 'voice_configurations', ['id'], unique=False)
    
    # Drop foreign key from voice_commands before dropping unique constraint on voice_sessions
    op.drop_constraint('voice_commands_session_id_fkey', 'voice_commands', type_='foreignkey')
    
    op.drop_index(op.f('ix_voice_sessions_appointment_id'), table_name='voice_sessions')
    op.drop_index(op.f('ix_voice_sessions_user_id'), table_name='voice_sessions')
    op.drop_constraint(op.f('voice_sessions_session_id_key'), 'voice_sessions', type_='unique')
    op.create_index(op.f('ix_voice_sessions_id'), 'voice_sessions', ['id'], unique=False)
    
    # Recreate foreign key if needed (check if voice_commands table still references session_id)
    # Note: The foreign key may not be recreated if the model no longer uses it
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_voice_sessions_id'), table_name='voice_sessions')
    op.create_unique_constraint(op.f('voice_sessions_session_id_key'), 'voice_sessions', ['session_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_voice_sessions_user_id'), 'voice_sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_voice_sessions_appointment_id'), 'voice_sessions', ['appointment_id'], unique=False)
    op.drop_index(op.f('ix_voice_configurations_id'), table_name='voice_configurations')
    op.create_index(op.f('ix_voice_configurations_user_id'), 'voice_configurations', ['user_id'], unique=False)
    op.create_index(op.f('ix_voice_configurations_clinic_id'), 'voice_configurations', ['clinic_id'], unique=False)
    op.alter_column('voice_configurations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_index(op.f('ix_voice_commands_id'), table_name='voice_commands')
    op.create_index(op.f('ix_voice_commands_session_id'), 'voice_commands', ['session_id'], unique=False)
    op.create_index(op.f('idx_users_is_active'), 'users', ['is_active'], unique=False)
    op.drop_constraint(None, 'user_settings', type_='foreignkey')
    op.create_foreign_key(op.f('fk_user_settings_user'), 'user_settings', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_user_settings_id'), table_name='user_settings')
    op.drop_index(op.f('ix_user_settings_user_id'), table_name='user_settings')
    op.create_index(op.f('ix_user_settings_user_id'), 'user_settings', ['user_id'], unique=False)
    op.create_unique_constraint(op.f('user_settings_user_id_key'), 'user_settings', ['user_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('user_settings', 'security',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('user_settings', 'appearance',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('user_settings', 'privacy',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('user_settings', 'notifications',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.create_unique_constraint(op.f('user_roles_name_key'), 'user_roles', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_tiss_versions_id'), table_name='tiss_versions')
    op.create_unique_constraint(op.f('tiss_versions_version_key'), 'tiss_versions', ['version'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_tiss_tuss_version_history_id'), table_name='tiss_tuss_version_history')
    op.alter_column('tiss_tuss_version_history', 'motivo',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_tiss_tuss_codes_id'), table_name='tiss_tuss_codes')
    op.alter_column('tiss_templates', 'variables',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_tiss_statements_id'), table_name='tiss_statements')
    op.drop_index('ix_tiss_statements_clinic_tipo', table_name='tiss_statements')
    op.drop_index(op.f('ix_tiss_sadt_guides_id'), table_name='tiss_sadt_guides')
    op.drop_index('ix_tiss_sadt_guides_clinic_status', table_name='tiss_sadt_guides')
    op.drop_index(op.f('ix_tiss_individual_fees_id'), table_name='tiss_individual_fees')
    op.drop_index(op.f('ix_tiss_hospitalization_guides_id'), table_name='tiss_hospitalization_guides')
    op.drop_index('ix_tiss_hospitalization_guides_clinic_status', table_name='tiss_hospitalization_guides')
    op.drop_index(op.f('ix_tiss_consultation_guides_id'), table_name='tiss_consultation_guides')
    op.drop_index('ix_tiss_consultation_guides_clinic_status', table_name='tiss_consultation_guides')
    op.drop_constraint('uq_tiss_config_clinic', 'tiss_config', type_='unique')
    op.create_index(op.f('uq_tiss_config_clinic'), 'tiss_config', ['clinic_id'], unique=True)
    op.create_unique_constraint(op.f('tiss_config_clinic_id_key'), 'tiss_config', ['clinic_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('tiss_config', 'tiss',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('tiss_config', 'defaults',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('tiss_config', 'operadora',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('tiss_config', 'prestador',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index(op.f('ix_tiss_batches_id'), table_name='tiss_batches')
    op.drop_index('ix_tiss_batches_clinic_status', table_name='tiss_batches')
    op.drop_index(op.f('ix_tiss_audit_logs_id'), table_name='tiss_audit_logs')
    op.drop_index('ix_tiss_audit_logs_entity', table_name='tiss_audit_logs')
    op.drop_index('ix_tiss_audit_logs_clinic_created', table_name='tiss_audit_logs')
    op.create_index(op.f('ix_tiss_audit_logs_entity_type_id'), 'tiss_audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.drop_index(op.f('ix_tiss_attachments_id'), table_name='tiss_attachments')
    op.drop_index('ix_tiss_attachments_guide', table_name='tiss_attachments')
    op.alter_column('tasks', 'priority',
               existing_type=sa.Enum('LOW', 'MEDIUM', 'HIGH', name='taskpriority', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'Média'::character varying"))
    op.drop_constraint(None, 'symptom_icd10_mappings', type_='foreignkey')
    op.create_foreign_key(op.f('symptom_icd10_mappings_symptom_id_fkey'), 'symptom_icd10_mappings', 'symptoms', ['symptom_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_symptom_icd10_mappings_symptom_id'), table_name='symptom_icd10_mappings')
    op.drop_index(op.f('ix_symptom_icd10_mappings_icd10_code'), table_name='symptom_icd10_mappings')
    op.create_index(op.f('ix_support_tickets_patient_id'), 'support_tickets', ['patient_id'], unique=False)
    op.create_index(op.f('ix_support_tickets_clinic_id'), 'support_tickets', ['clinic_id'], unique=False)
    op.create_index(op.f('idx_stock_movements_timestamp'), 'stock_movements', ['timestamp'], unique=False)
    op.create_index(op.f('idx_stock_movements_clinic_id'), 'stock_movements', ['clinic_id'], unique=False)
    op.drop_constraint(None, 'push_subscriptions', type_='foreignkey')
    op.create_foreign_key(op.f('fk_push_subscriptions_user_id'), 'push_subscriptions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_push_subscriptions_id'), table_name='push_subscriptions')
    op.create_index(op.f('ix_push_subscriptions_endpoint'), 'push_subscriptions', ['endpoint'], unique=False)
    op.create_index(op.f('idx_products_is_active'), 'products', ['is_active'], unique=False)
    op.create_index(op.f('ix_payments_invoice_id'), 'payments', ['invoice_id'], unique=False)
    op.create_index(op.f('idx_payments_paid_at'), 'payments', ['paid_at'], unique=False)
    op.create_index(op.f('idx_patients_is_active'), 'patients', ['is_active'], unique=False)
    op.create_index(op.f('idx_patients_created_at'), 'patients', ['created_at'], unique=False)
    op.drop_constraint(None, 'patient_telemetry', type_='foreignkey')
    op.drop_constraint(None, 'patient_telemetry', type_='foreignkey')
    op.drop_constraint(None, 'patient_telemetry', type_='foreignkey')
    op.create_foreign_key(op.f('patient_telemetry_clinic_id_fkey'), 'patient_telemetry', 'clinics', ['clinic_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('patient_telemetry_recorded_by_fkey'), 'patient_telemetry', 'users', ['recorded_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('patient_telemetry_patient_id_fkey'), 'patient_telemetry', 'patients', ['patient_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_patient_calls_id'), table_name='patient_calls')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(op.f('messages_sender_id_fkey'), 'messages', 'users', ['sender_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('messages_thread_id_fkey'), 'messages', 'message_threads', ['thread_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_messages_thread_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.create_index(op.f('idx_messages_thread_id'), 'messages', ['thread_id'], unique=False)
    op.create_index(op.f('idx_messages_sender_id'), 'messages', ['sender_id'], unique=False)
    op.create_index(op.f('idx_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.alter_column('messages', 'medical_context',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('messages', 'attachments',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('messages', 'status',
               existing_type=sa.Enum('SENT', 'DELIVERED', 'READ', name='messagestatus', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'sent'::character varying"))
    op.drop_constraint(None, 'message_threads', type_='foreignkey')
    op.drop_constraint(None, 'message_threads', type_='foreignkey')
    op.drop_constraint(None, 'message_threads', type_='foreignkey')
    op.create_foreign_key(op.f('message_threads_patient_id_fkey'), 'message_threads', 'patients', ['patient_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('message_threads_provider_id_fkey'), 'message_threads', 'users', ['provider_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('message_threads_clinic_id_fkey'), 'message_threads', 'clinics', ['clinic_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_message_threads_provider_id'), table_name='message_threads')
    op.drop_index(op.f('ix_message_threads_patient_id'), table_name='message_threads')
    op.drop_index(op.f('ix_message_threads_id'), table_name='message_threads')
    op.drop_index(op.f('ix_message_threads_clinic_id'), table_name='message_threads')
    op.create_index(op.f('idx_message_threads_provider_id'), 'message_threads', ['provider_id'], unique=False)
    op.create_index(op.f('idx_message_threads_patient_id'), 'message_threads', ['patient_id'], unique=False)
    op.create_index(op.f('idx_message_threads_clinic_id'), 'message_threads', ['clinic_id'], unique=False)
    op.drop_index(op.f('ix_medical_terms_id'), table_name='medical_terms')
    op.create_index(op.f('ix_medical_terms_category'), 'medical_terms', ['category'], unique=False)
    op.alter_column('medical_terms', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_index(op.f('idx_invoices_status'), 'invoices', ['status'], unique=False)
    op.create_index(op.f('idx_invoices_issue_date'), 'invoices', ['issue_date'], unique=False)
    op.drop_constraint(None, 'icd10_subcategories', type_='unique')
    op.create_index(op.f('ix_icd10_subcategories_category_code'), 'icd10_subcategories', ['category_code'], unique=False)
    op.drop_index('ix_icd10_search_parent', table_name='icd10_search_index')
    op.drop_index('ix_icd10_search_code', table_name='icd10_search_index')
    op.create_index(op.f('ix_icd10_search_index_parent_code'), 'icd10_search_index', ['parent_code'], unique=False)
    op.create_index(op.f('ix_icd10_search_index_code'), 'icd10_search_index', ['code'], unique=False)
    op.drop_constraint(None, 'icd10_groups', type_='unique')
    op.create_index(op.f('ix_icd10_groups_chapter_code'), 'icd10_groups', ['chapter_code'], unique=False)
    op.drop_constraint(None, 'icd10_chapters', type_='unique')
    op.drop_constraint(None, 'icd10_categories', type_='unique')
    op.drop_index('ix_icd10_categories_code', table_name='icd10_categories')
    op.create_index(op.f('ix_icd10_categories_code'), 'icd10_categories', ['code'], unique=True)
    op.create_index(op.f('ix_icd10_categories_group_code'), 'icd10_categories', ['group_code'], unique=False)
    op.create_index(op.f('ix_help_articles_clinic_id'), 'help_articles', ['clinic_id'], unique=False)
    op.alter_column('expenses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('expenses', 'status',
               existing_type=sa.Enum('PENDING', 'PAID', 'CANCELLED', name='expensestatus', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    # Skip entitlements column changes - they cause foreign key type mismatch
    # op.alter_column('entitlements', 'license_id', ...)
    # op.alter_column('entitlements', 'id', ...)
    op.drop_constraint(None, 'document_signatures', type_='foreignkey')
    op.drop_constraint(None, 'document_signatures', type_='foreignkey')
    op.create_foreign_key(op.f('document_signatures_doctor_id_fkey'), 'document_signatures', 'users', ['doctor_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('document_signatures_clinic_id_fkey'), 'document_signatures', 'clinics', ['clinic_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_document_signatures_doc_type_id'), 'document_signatures', ['document_type', 'document_id'], unique=False)
    op.alter_column('document_signatures', 'status',
               existing_type=sa.Enum('PENDING', 'SIGNED', 'REVOKED', 'EXPIRED', name='signaturestatus', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'signed'::character varying"))
    op.alter_column('document_signatures', 'document_type',
               existing_type=sa.Enum('PRESCRIPTION', 'CERTIFICATE', 'CONSULTATION_REPORT', 'EXAM_REQUEST', 'OTHER', name='documenttype', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.create_index(op.f('idx_clinical_records_created_at'), 'clinical_records', ['created_at'], unique=False)
    op.alter_column('budgets', 'status',
               existing_type=sa.Enum('DRAFT', 'SENT', 'ACCEPTED', 'REJECTED', 'CONVERTED', 'EXPIRED', name='budgetstatus', native_enum=False),
               type_=postgresql.ENUM('draft', 'sent', 'accepted', 'rejected', 'converted', 'expired', name='budgetstatus'),
               existing_nullable=False)
    # Skip activations column changes - they cause foreign key type mismatch
    # op.alter_column('activations', 'license_id', ...)
    # op.alter_column('activations', 'id', ...)
    op.create_table('migration_jobs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('clinic_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('type', postgresql.ENUM('patients', 'appointments', 'clinical', 'financial', name='migrationtype'), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'running', 'completed', 'failed', 'rolled_back', name='migrationstatus'), server_default=sa.text("'pending'::migrationstatus"), autoincrement=False, nullable=False),
    sa.Column('input_format', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('source_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('migration_jobs_pkey'))
    )
    op.create_index(op.f('ix_migration_jobs_id'), 'migration_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_migration_jobs_created_by'), 'migration_jobs', ['created_by'], unique=False)
    op.create_index(op.f('ix_migration_jobs_clinic_id'), 'migration_jobs', ['clinic_id'], unique=False)
    
    # Drop return visit management tables
    op.drop_index('ix_return_visit_approvals_created_at', table_name='return_visit_approvals')
    op.drop_index('ix_return_visit_approvals_status', table_name='return_visit_approvals')
    op.drop_index(op.f('ix_return_visit_approvals_id'), table_name='return_visit_approvals')
    op.drop_table('return_visit_approvals')
    op.drop_index('ix_return_visit_configs_clinic_doctor', table_name='return_visit_configs')
    op.drop_index(op.f('ix_return_visit_configs_id'), table_name='return_visit_configs')
    op.drop_table('return_visit_configs')
    
    op.drop_index(op.f('ix_system_logs_user_id'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_timestamp'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_source'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_level'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_id'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_clinic_id'), table_name='system_logs')
    op.drop_table('system_logs')
    op.drop_index(op.f('ix_preauth_requests_id'), table_name='preauth_requests')
    op.drop_table('preauth_requests')
    op.drop_index(op.f('ix_insurance_plans_name'), table_name='insurance_plans')
    op.drop_index(op.f('ix_insurance_plans_id'), table_name='insurance_plans')
    op.drop_index(op.f('ix_insurance_plans_ans_registration'), table_name='insurance_plans')
    op.drop_table('insurance_plans')
    # ### end Alembic commands ###
