"""Add TISS insurance structure tables

Revision ID: 4f5276f90f35
Revises: 7a605a27f1ac
Create Date: 2026-01-29 14:39:15.535309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f5276f90f35'
down_revision: Union[str, None] = '7a605a27f1ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tiss_insurance_companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('razao_social', sa.String(length=200), nullable=True),
    sa.Column('cnpj', sa.String(length=18), nullable=False),
    sa.Column('registro_ans', sa.String(length=6), nullable=False),
    sa.Column('codigo_operadora', sa.String(length=20), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('endereco', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tiss_insurance_companies_clinic_cnpj', 'tiss_insurance_companies', ['clinic_id', 'cnpj'], unique=False)
    op.create_index(op.f('ix_tiss_insurance_companies_clinic_id'), 'tiss_insurance_companies', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_tiss_insurance_companies_cnpj'), 'tiss_insurance_companies', ['cnpj'], unique=True)
    op.create_index(op.f('ix_tiss_insurance_companies_codigo_operadora'), 'tiss_insurance_companies', ['codigo_operadora'], unique=False)
    op.create_index(op.f('ix_tiss_insurance_companies_id'), 'tiss_insurance_companies', ['id'], unique=False)
    op.create_index(op.f('ix_tiss_insurance_companies_is_active'), 'tiss_insurance_companies', ['is_active'], unique=False)
    op.create_index(op.f('ix_tiss_insurance_companies_nome'), 'tiss_insurance_companies', ['nome'], unique=False)
    op.create_index(op.f('ix_tiss_insurance_companies_registro_ans'), 'tiss_insurance_companies', ['registro_ans'], unique=False)
    op.create_table('tiss_insurance_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('insurance_company_id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('nome_plano', sa.String(length=200), nullable=False),
    sa.Column('codigo_plano', sa.String(length=50), nullable=True),
    sa.Column('numero_plano_ans', sa.String(length=20), nullable=True),
    sa.Column('cobertura_percentual', sa.Numeric(precision=5, scale=2), server_default='100.00', nullable=False),
    sa.Column('requer_autorizacao', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('limite_anual', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('limite_por_procedimento', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('data_inicio_vigencia', sa.Date(), nullable=True),
    sa.Column('data_fim_vigencia', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('configuracoes_extras', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['insurance_company_id'], ['tiss_insurance_companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tiss_insurance_plans_clinic_id'), 'tiss_insurance_plans', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_tiss_insurance_plans_codigo_plano'), 'tiss_insurance_plans', ['codigo_plano'], unique=False)
    op.create_index('ix_tiss_insurance_plans_company_plan', 'tiss_insurance_plans', ['insurance_company_id', 'codigo_plano'], unique=False)
    op.create_index(op.f('ix_tiss_insurance_plans_id'), 'tiss_insurance_plans', ['id'], unique=False)
    op.create_index(op.f('ix_tiss_insurance_plans_insurance_company_id'), 'tiss_insurance_plans', ['insurance_company_id'], unique=False)
    op.create_index(op.f('ix_tiss_insurance_plans_is_active'), 'tiss_insurance_plans', ['is_active'], unique=False)
    op.create_index(op.f('ix_tiss_insurance_plans_nome_plano'), 'tiss_insurance_plans', ['nome_plano'], unique=False)
    op.create_table('tiss_tuss_plan_coverage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tuss_code_id', sa.Integer(), nullable=False),
    sa.Column('insurance_plan_id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('coberto', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('cobertura_percentual', sa.Numeric(precision=5, scale=2), server_default='100.00', nullable=False),
    sa.Column('valor_tabela', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('valor_contratual', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('valor_coparticipacao', sa.Numeric(precision=12, scale=2), server_default='0.00', nullable=True),
    sa.Column('valor_franquia', sa.Numeric(precision=12, scale=2), server_default='0.00', nullable=True),
    sa.Column('requer_autorizacao', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('prazo_autorizacao_dias', sa.Integer(), nullable=True),
    sa.Column('limite_quantidade', sa.Integer(), nullable=True),
    sa.Column('limite_periodo_dias', sa.Integer(), nullable=True),
    sa.Column('data_inicio_vigencia', sa.Date(), nullable=False),
    sa.Column('data_fim_vigencia', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('regras_especiais', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['insurance_plan_id'], ['tiss_insurance_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tuss_code_id'], ['tiss_tuss_codes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tiss_tuss_plan_coverage_clinic_id'), 'tiss_tuss_plan_coverage', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_tiss_tuss_plan_coverage_coberto'), 'tiss_tuss_plan_coverage', ['coberto'], unique=False)
    op.create_index(op.f('ix_tiss_tuss_plan_coverage_data_fim_vigencia'), 'tiss_tuss_plan_coverage', ['data_fim_vigencia'], unique=False)
    op.create_index(op.f('ix_tiss_tuss_plan_coverage_data_inicio_vigencia'), 'tiss_tuss_plan_coverage', ['data_inicio_vigencia'], unique=False)
    op.create_index(op.f('ix_tiss_tuss_plan_coverage_id'), 'tiss_tuss_plan_coverage', ['id'], unique=False)
    op.create_index(op.f('ix_tiss_tuss_plan_coverage_insurance_plan_id'), 'tiss_tuss_plan_coverage', ['insurance_plan_id'], unique=False)
    op.create_index(op.f('ix_tiss_tuss_plan_coverage_is_active'), 'tiss_tuss_plan_coverage', ['is_active'], unique=False)
    op.create_index(op.f('ix_tiss_tuss_plan_coverage_tuss_code_id'), 'tiss_tuss_plan_coverage', ['tuss_code_id'], unique=False)
    op.create_index('ix_tiss_tuss_plan_coverage_tuss_plan', 'tiss_tuss_plan_coverage', ['tuss_code_id', 'insurance_plan_id'], unique=False)
    op.create_index('ix_tiss_tuss_plan_coverage_vigencia', 'tiss_tuss_plan_coverage', ['data_inicio_vigencia', 'data_fim_vigencia'], unique=False)
    op.create_table('tiss_tuss_load_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('insurance_company_id', sa.Integer(), nullable=True),
    sa.Column('tuss_plan_coverage_id', sa.Integer(), nullable=True),
    sa.Column('tipo_carga', sa.String(length=50), nullable=False),
    sa.Column('nome_arquivo', sa.String(length=255), nullable=False),
    sa.Column('total_registros', sa.Integer(), server_default='0', nullable=False),
    sa.Column('registros_inseridos', sa.Integer(), server_default='0', nullable=False),
    sa.Column('registros_atualizados', sa.Integer(), server_default='0', nullable=False),
    sa.Column('registros_erro', sa.Integer(), server_default='0', nullable=False),
    sa.Column('versao_tuss', sa.String(length=20), nullable=True),
    sa.Column('data_referencia', sa.Date(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('erros', sa.JSON(), nullable=True),
    sa.Column('avisos', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['insurance_company_id'], ['tiss_insurance_companies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tuss_plan_coverage_id'], ['tiss_tuss_plan_coverage.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tiss_load_history_clinic_tipo', 'tiss_tuss_load_history', ['clinic_id', 'tipo_carga'], unique=False)
    op.create_index('ix_tiss_load_history_created_at', 'tiss_tuss_load_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_tiss_tuss_load_history_clinic_id'), 'tiss_tuss_load_history', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_tiss_tuss_load_history_created_at'), 'tiss_tuss_load_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_tiss_tuss_load_history_id'), 'tiss_tuss_load_history', ['id'], unique=False)
    op.create_index(op.f('ix_tiss_tuss_load_history_insurance_company_id'), 'tiss_tuss_load_history', ['insurance_company_id'], unique=False)
    op.create_index(op.f('ix_tiss_tuss_load_history_tipo_carga'), 'tiss_tuss_load_history', ['tipo_carga'], unique=False)
    op.alter_column('activations', 'id',
               existing_type=sa.UUID(),
               type_=sa.CHAR(length=36),
               existing_nullable=False)
    op.alter_column('activations', 'license_id',
               existing_type=sa.UUID(),
               type_=sa.CHAR(length=36),
               existing_nullable=False)
    op.alter_column('entitlements', 'id',
               existing_type=sa.UUID(),
               type_=sa.CHAR(length=36),
               existing_nullable=False)
    op.alter_column('entitlements', 'license_id',
               existing_type=sa.UUID(),
               type_=sa.CHAR(length=36),
               existing_nullable=False)
    op.create_index(op.f('ix_return_visit_approvals_appointment_id'), 'return_visit_approvals', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_return_visit_approvals_clinic_id'), 'return_visit_approvals', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_return_visit_approvals_doctor_id'), 'return_visit_approvals', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_return_visit_approvals_patient_id'), 'return_visit_approvals', ['patient_id'], unique=False)
    op.drop_index(op.f('ix_return_visit_configs_clinic_doctor'), table_name='return_visit_configs')
    op.create_index(op.f('ix_return_visit_configs_clinic_id'), 'return_visit_configs', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_return_visit_configs_doctor_id'), 'return_visit_configs', ['doctor_id'], unique=False)
    op.create_foreign_key(None, 'voice_commands', 'voice_sessions', ['session_id'], ['session_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'voice_commands', type_='foreignkey')
    op.drop_index(op.f('ix_return_visit_configs_doctor_id'), table_name='return_visit_configs')
    op.drop_index(op.f('ix_return_visit_configs_clinic_id'), table_name='return_visit_configs')
    op.create_index(op.f('ix_return_visit_configs_clinic_doctor'), 'return_visit_configs', ['clinic_id', 'doctor_id'], unique=False)
    op.drop_index(op.f('ix_return_visit_approvals_patient_id'), table_name='return_visit_approvals')
    op.drop_index(op.f('ix_return_visit_approvals_doctor_id'), table_name='return_visit_approvals')
    op.drop_index(op.f('ix_return_visit_approvals_clinic_id'), table_name='return_visit_approvals')
    op.drop_index(op.f('ix_return_visit_approvals_appointment_id'), table_name='return_visit_approvals')
    op.alter_column('entitlements', 'license_id',
               existing_type=sa.CHAR(length=36),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('entitlements', 'id',
               existing_type=sa.CHAR(length=36),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('activations', 'license_id',
               existing_type=sa.CHAR(length=36),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('activations', 'id',
               existing_type=sa.CHAR(length=36),
               type_=sa.UUID(),
               existing_nullable=False)
    op.drop_index(op.f('ix_tiss_tuss_load_history_tipo_carga'), table_name='tiss_tuss_load_history')
    op.drop_index(op.f('ix_tiss_tuss_load_history_insurance_company_id'), table_name='tiss_tuss_load_history')
    op.drop_index(op.f('ix_tiss_tuss_load_history_id'), table_name='tiss_tuss_load_history')
    op.drop_index(op.f('ix_tiss_tuss_load_history_created_at'), table_name='tiss_tuss_load_history')
    op.drop_index(op.f('ix_tiss_tuss_load_history_clinic_id'), table_name='tiss_tuss_load_history')
    op.drop_index('ix_tiss_load_history_created_at', table_name='tiss_tuss_load_history')
    op.drop_index('ix_tiss_load_history_clinic_tipo', table_name='tiss_tuss_load_history')
    op.drop_table('tiss_tuss_load_history')
    op.drop_index('ix_tiss_tuss_plan_coverage_vigencia', table_name='tiss_tuss_plan_coverage')
    op.drop_index('ix_tiss_tuss_plan_coverage_tuss_plan', table_name='tiss_tuss_plan_coverage')
    op.drop_index(op.f('ix_tiss_tuss_plan_coverage_tuss_code_id'), table_name='tiss_tuss_plan_coverage')
    op.drop_index(op.f('ix_tiss_tuss_plan_coverage_is_active'), table_name='tiss_tuss_plan_coverage')
    op.drop_index(op.f('ix_tiss_tuss_plan_coverage_insurance_plan_id'), table_name='tiss_tuss_plan_coverage')
    op.drop_index(op.f('ix_tiss_tuss_plan_coverage_id'), table_name='tiss_tuss_plan_coverage')
    op.drop_index(op.f('ix_tiss_tuss_plan_coverage_data_inicio_vigencia'), table_name='tiss_tuss_plan_coverage')
    op.drop_index(op.f('ix_tiss_tuss_plan_coverage_data_fim_vigencia'), table_name='tiss_tuss_plan_coverage')
    op.drop_index(op.f('ix_tiss_tuss_plan_coverage_coberto'), table_name='tiss_tuss_plan_coverage')
    op.drop_index(op.f('ix_tiss_tuss_plan_coverage_clinic_id'), table_name='tiss_tuss_plan_coverage')
    op.drop_table('tiss_tuss_plan_coverage')
    op.drop_index(op.f('ix_tiss_insurance_plans_nome_plano'), table_name='tiss_insurance_plans')
    op.drop_index(op.f('ix_tiss_insurance_plans_is_active'), table_name='tiss_insurance_plans')
    op.drop_index(op.f('ix_tiss_insurance_plans_insurance_company_id'), table_name='tiss_insurance_plans')
    op.drop_index(op.f('ix_tiss_insurance_plans_id'), table_name='tiss_insurance_plans')
    op.drop_index('ix_tiss_insurance_plans_company_plan', table_name='tiss_insurance_plans')
    op.drop_index(op.f('ix_tiss_insurance_plans_codigo_plano'), table_name='tiss_insurance_plans')
    op.drop_index(op.f('ix_tiss_insurance_plans_clinic_id'), table_name='tiss_insurance_plans')
    op.drop_table('tiss_insurance_plans')
    op.drop_index(op.f('ix_tiss_insurance_companies_registro_ans'), table_name='tiss_insurance_companies')
    op.drop_index(op.f('ix_tiss_insurance_companies_nome'), table_name='tiss_insurance_companies')
    op.drop_index(op.f('ix_tiss_insurance_companies_is_active'), table_name='tiss_insurance_companies')
    op.drop_index(op.f('ix_tiss_insurance_companies_id'), table_name='tiss_insurance_companies')
    op.drop_index(op.f('ix_tiss_insurance_companies_codigo_operadora'), table_name='tiss_insurance_companies')
    op.drop_index(op.f('ix_tiss_insurance_companies_cnpj'), table_name='tiss_insurance_companies')
    op.drop_index(op.f('ix_tiss_insurance_companies_clinic_id'), table_name='tiss_insurance_companies')
    op.drop_index('ix_tiss_insurance_companies_clinic_cnpj', table_name='tiss_insurance_companies')
    op.drop_table('tiss_insurance_companies')
    # ### end Alembic commands ###
